/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HimayahRouteImport } from './routes/himayah'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HimayahIndexRouteImport } from './routes/himayah/index'
import { Route as HimayahNewRouteImport } from './routes/himayah/new'
import { Route as HimayahLoginRouteImport } from './routes/himayah/login'
import { Route as SectionCategoryRouteImport } from './routes/$section.$category'
import { Route as HimayahEditIdRouteImport } from './routes/himayah/edit.$id'
import { Route as SectionCategoryEntryRouteImport } from './routes/$section.$category.$entry'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HimayahRoute = HimayahRouteImport.update({
  id: '/himayah',
  path: '/himayah',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HimayahIndexRoute = HimayahIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HimayahRoute,
} as any)
const HimayahNewRoute = HimayahNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HimayahRoute,
} as any)
const HimayahLoginRoute = HimayahLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HimayahRoute,
} as any)
const SectionCategoryRoute = SectionCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => SectionRoute,
} as any)
const HimayahEditIdRoute = HimayahEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => HimayahRoute,
} as any)
const SectionCategoryEntryRoute = SectionCategoryEntryRouteImport.update({
  id: '/$entry',
  path: '/$entry',
  getParentRoute: () => SectionCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/himayah': typeof HimayahRouteWithChildren
  '/search': typeof SearchRoute
  '/$section/$category': typeof SectionCategoryRouteWithChildren
  '/himayah/login': typeof HimayahLoginRoute
  '/himayah/new': typeof HimayahNewRoute
  '/himayah/': typeof HimayahIndexRoute
  '/$section/$category/$entry': typeof SectionCategoryEntryRoute
  '/himayah/edit/$id': typeof HimayahEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/search': typeof SearchRoute
  '/$section/$category': typeof SectionCategoryRouteWithChildren
  '/himayah/login': typeof HimayahLoginRoute
  '/himayah/new': typeof HimayahNewRoute
  '/himayah': typeof HimayahIndexRoute
  '/$section/$category/$entry': typeof SectionCategoryEntryRoute
  '/himayah/edit/$id': typeof HimayahEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/himayah': typeof HimayahRouteWithChildren
  '/search': typeof SearchRoute
  '/$section/$category': typeof SectionCategoryRouteWithChildren
  '/himayah/login': typeof HimayahLoginRoute
  '/himayah/new': typeof HimayahNewRoute
  '/himayah/': typeof HimayahIndexRoute
  '/$section/$category/$entry': typeof SectionCategoryEntryRoute
  '/himayah/edit/$id': typeof HimayahEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/himayah'
    | '/search'
    | '/$section/$category'
    | '/himayah/login'
    | '/himayah/new'
    | '/himayah/'
    | '/$section/$category/$entry'
    | '/himayah/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/search'
    | '/$section/$category'
    | '/himayah/login'
    | '/himayah/new'
    | '/himayah'
    | '/$section/$category/$entry'
    | '/himayah/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/himayah'
    | '/search'
    | '/$section/$category'
    | '/himayah/login'
    | '/himayah/new'
    | '/himayah/'
    | '/$section/$category/$entry'
    | '/himayah/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRouteWithChildren
  HimayahRoute: typeof HimayahRouteWithChildren
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himayah': {
      id: '/himayah'
      path: '/himayah'
      fullPath: '/himayah'
      preLoaderRoute: typeof HimayahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himayah/': {
      id: '/himayah/'
      path: '/'
      fullPath: '/himayah/'
      preLoaderRoute: typeof HimayahIndexRouteImport
      parentRoute: typeof HimayahRoute
    }
    '/himayah/new': {
      id: '/himayah/new'
      path: '/new'
      fullPath: '/himayah/new'
      preLoaderRoute: typeof HimayahNewRouteImport
      parentRoute: typeof HimayahRoute
    }
    '/himayah/login': {
      id: '/himayah/login'
      path: '/login'
      fullPath: '/himayah/login'
      preLoaderRoute: typeof HimayahLoginRouteImport
      parentRoute: typeof HimayahRoute
    }
    '/$section/$category': {
      id: '/$section/$category'
      path: '/$category'
      fullPath: '/$section/$category'
      preLoaderRoute: typeof SectionCategoryRouteImport
      parentRoute: typeof SectionRoute
    }
    '/himayah/edit/$id': {
      id: '/himayah/edit/$id'
      path: '/edit/$id'
      fullPath: '/himayah/edit/$id'
      preLoaderRoute: typeof HimayahEditIdRouteImport
      parentRoute: typeof HimayahRoute
    }
    '/$section/$category/$entry': {
      id: '/$section/$category/$entry'
      path: '/$entry'
      fullPath: '/$section/$category/$entry'
      preLoaderRoute: typeof SectionCategoryEntryRouteImport
      parentRoute: typeof SectionCategoryRoute
    }
  }
}

interface SectionCategoryRouteChildren {
  SectionCategoryEntryRoute: typeof SectionCategoryEntryRoute
}

const SectionCategoryRouteChildren: SectionCategoryRouteChildren = {
  SectionCategoryEntryRoute: SectionCategoryEntryRoute,
}

const SectionCategoryRouteWithChildren = SectionCategoryRoute._addFileChildren(
  SectionCategoryRouteChildren,
)

interface SectionRouteChildren {
  SectionCategoryRoute: typeof SectionCategoryRouteWithChildren
}

const SectionRouteChildren: SectionRouteChildren = {
  SectionCategoryRoute: SectionCategoryRouteWithChildren,
}

const SectionRouteWithChildren =
  SectionRoute._addFileChildren(SectionRouteChildren)

interface HimayahRouteChildren {
  HimayahLoginRoute: typeof HimayahLoginRoute
  HimayahNewRoute: typeof HimayahNewRoute
  HimayahIndexRoute: typeof HimayahIndexRoute
  HimayahEditIdRoute: typeof HimayahEditIdRoute
}

const HimayahRouteChildren: HimayahRouteChildren = {
  HimayahLoginRoute: HimayahLoginRoute,
  HimayahNewRoute: HimayahNewRoute,
  HimayahIndexRoute: HimayahIndexRoute,
  HimayahEditIdRoute: HimayahEditIdRoute,
}

const HimayahRouteWithChildren =
  HimayahRoute._addFileChildren(HimayahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRouteWithChildren,
  HimayahRoute: HimayahRouteWithChildren,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
